version: '3.8'

services:
  sessionerr:
    build: .
    environment:
      - USERNAME=
      - HOST=http://qbitorrent_url
      - PASSWORD=password
      - SESSIONDIR= #left blank if you not sure what to use, it point to your /BT_Backup by default
      - CROSSSEED=http://crossseed_url
    networks:
      - cross-seed_sample #configure your network that cross-seed and qbit-torrent use here
      - qbit-torrent_sample


