version: '3.8'

services:
  sessionerr:
    build: .
    environment:
      - USERNAME=<username>
      - HOST=<HTTP://qbittorrent_host>
      - PASSWORD=<password>
      - SESSIONDIR=<session_dir>
      - CROSSSEED=<HTTP://cross_seed_host>
    networks:
      - cross-seeds_default
      - bridge

networks:
  cross-seeds_default:
    external: true
  bridge:
    external: true
